### ISSUE TITLE
Find kubernetes logs in OpenShift

### ISSUE THREAD

**Issue by mmmmmmpc** [amitkumarj441/gsoc17-cncf#6]
Find kubernetes logs in openshift such as logs for:
- Kube Master
- API access
- Kubelet
- Kube proxy
and create a filter for them. 
If required change origin-node and/or origin-master for the appropriate field the log is coming from

**Comment by amitkumarj441** [comment]
@mperezco but what I know is that openshift doesn't run separate kube-apiserver, kube-proxy, kube-dns, kubelet, kube-controller-manager, or kube-scheduler, they have `openshift start master api`, `openshift start master controllers`, `openshift start node` those actually contains the actual kube components themselves.

**Comment by mmmmmmpc** [comment]
Yes, the components are packaged to be easily deployed and managed. We have to find where are getting their logs sent (at least some to journald) and structure them

**Comment by amitkumarj441** [comment]
@mperezco `/var/log/containers/*`  <- kubelet creates symbolink links to real docker files, those files have the container info in the name, note that logs needs to be mounted so Fluentd can read them.

**Comment by mmmmmmpc** [comment]
Let's consider the use case in which base components are not deployed as a container (the ViaQ install is an example) and logs come via Journald

**Comment by mmmmmmpc** [comment]
logs get ingested via journald.
They are processed and get the tag
```_SYSTEMD_UNIT=origin-master ```
and
```_SYSTEMD_UNIT=origin-node ```

**Comment by mmmmmmpc** [comment]
For OpenShift Container Platform ```òrigin``` gets substituted by ```atomic-openshift```

**Comment by mmmmmmpc** [comment]
@amitkumarj441 ... do you feel comfortable to close this issue?

**Comment by amitkumarj441** [comment]
Yeah @mperezco .
Closing the issue now :+1: 

Thanks!
