### ISSUE TITLE
Tag Fluentd Image

### ISSUE THREAD

**Issue by amitkumarj441** [amitkumarj441/gsoc17-cncf#8]
@mperezco I just created a [daemonSet](https://github.com/amitkumarj441/gsoc17-cncf/blob/master/codes/fluentd-kubernetes/fluentd-ds.yml) using my journald service.

Please point which fluentd image to use in yaml.

**Comment by mmmmmmpc** [comment]
docker.io/openshift/origin-logging-fluentd         v1.5.1
